name: C Runtime Test Action (Local Runner)

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string

defaults:
  run:
    shell: bash
jobs:
  _:
    runs-on: self-hosted
    steps:
        # Download latest commit
      - uses: actions/checkout@v4

        # Build source using make
      - name: Testing Runtime
        working-directory: ${{ inputs.directory }}
        run: make
